#!/bin/bash
# Author:why (E-mail:wuhaoyu2222@gmail.com)

# 执行循环提取镜像文件中的每一行
count=0
declare -a pings
for i in $(cat ubuntu_mirrors)
	do
		echo 'ping...'
		echo `ping $i -c 3 | grep 64 | awk '{print $7}' | awk 'BEGIN{FS="="}{print $2}' | awk '{sum+=$1}END{print sum/NR}' | awk 'BEGIN{FS="."}{print $1}'` " $i"  >> tmp.txt
		let count+=1
	done

# 取出最小值
min=`awk 'BEGIN {min = 65536} {if ($1+0 < min+0) min=$1} END {print min}' tmp.txt`
new=`grep $min tmp.txt | awk '{print $2}'`
rm -rf tmp.txt

# 更新源
sudo cp /etc/apt/sources.list /etc/apt/sources.list.bak
old=`sed -e '/#/d' /etc/apt/sources.list | sed -e '/security/d' | awk 'BEGIN{FS="/"}{print $3}' | grep -v '^$'| sed -n '1p'`
sudo sed -i s/$old/$new/g /etc/apt/sources.list
sudo apt-get update
sudo apt-get upgrade
